createRevision:
  name: ${self:custom.base}-create-revision
  handler: services/revisiones/src/create-revision.main
  events:
    - httpApi: 'POST /rev/revision'
  package:
    include:
      - services/revisiones/src/create-revision.js
      - lib/errors/database-error.js

getRevisiones:
  name: ${self:custom.base}-get-revisiones
  handler: services/revisiones/src/get-revisiones.main
  events:
    - httpApi: 'GET /rev/revision/{limit}/{start}/{busqueda}'
  package:
    include:
      - services/revisiones/src/get-revisiones.js
      - lib/errors/database-error.js

getRevisionByPunto:
  name: ${self:custom.base}-get-revision-by-punto
  handler: services/revisiones/src/get-revision-by-punto.main
  events:
    - httpApi: 'GET /rev/revision/byPunto/{_id}'
  package:
    include:
      - services/revisiones/src/get-revision-by-punto.js
      - lib/errors/database-error.js  

getRevisionById:
  name: ${self:custom.base}-get-revision-by-id
  handler: services/revisiones/src/get-revision-by-id.main
  events:
    - httpApi: 'GET /rev/revision/byId/{_id}'
  package:
    include:
      - services/revisiones/src/get-revision-by-id.js
      - lib/errors/database-error.js

addImages:
  name: ${self:custom.base}-add-images
  handler: services/revisiones/src/add-images.main
  timeout: 25
  events:
    - httpApi: 'PUT /rev/revision/add-images'
  environment:
    BUCKET: codegas
  package:
    include:
      - services/revisiones/src/add-images.js
      - lib/errors/database-error.js
      - lib/image.js
      - lib/responses.js

removeImages:
  name: ${self:custom.base}-add-images
  handler: services/revisiones/src/add-images.main
  timeout: 25
  events:
    - httpApi: 'PUT /tan/tanque/images/{idTanque}/{type}'
  environment:
    BUCKET: codegas
  package:
    include:
      - services/revisiones/src/add-images.js
      - lib/errors/database-error.js
      - lib/image.js
      - lib/responses.js


# editVehiculo:
#   name: ${self:custom.base}-edit-vehiculo
#   handler: services/vehiculos/src/edit-vehiculo.main
#   events:
#     - httpApi: 'PUT /veh/vehiculo/editar/{_id}'
#   package:
#     include:
#       - services/vehiculos/src/edit-vehiculo.js
#       - lib/errors/database-error.js

# changeStateVehiculo:
#   name: ${self:custom.base}-change-state-vehiculo
#   handler: services/vehiculos/src/change-state-vehiculo.main
#   events:
#     - httpApi: 'GET /veh/vehiculo/cambiarEstado/{_id}/{estado}'
#   package:
#     include:
#       - services/vehiculos/src/change-state-vehiculo.js
#       - lib/errors/database-error.js

# deleteVehiculo:
#   name: ${self:custom.base}-delete-vehiculo
#   handler: services/vehiculos/src/delete-vehiculo.main
#   events:
#     - httpApi: 'GET /veh/vehiculo/eliminar/{_id}/{estado}'
#   package:
#     include:
#       - services/vehiculos/src/delete-vehiculo.js
#       - lib/errors/database-error.js

# desvincularConductorVehiculo:
#   name: ${self:custom.base}-desvincular-conductor-vehiculo
#   handler: services/vehiculos/src/desvincular-conductor-vehiculo.main
#   events:
#     - httpApi: 'GET /veh/vehiculo/desvincularConductor/{_id}'
#   package:
#     include:
#       - services/vehiculos/src/desvincular-conductor-vehiculo.js
#       - lib/errors/database-error.js

# asignarConductorVehiculo:
#   name: ${self:custom.base}-asignar-conductor-vehiculo
#   handler: services/vehiculos/src/asignar-conductor-vehiculo.main
#   events:
#     - httpApi: 'GET /veh/vehiculo/asignarConductor/{_id}/{_idConductor}'
#   package:
#     include:
#       - services/vehiculos/src/asignar-conductor-vehiculo.js
#       - lib/errors/database-error.js

# getVehiculoById:
#   name: ${self:custom.base}-get-vehiculo-by-id
#   handler: services/vehiculos/src/get-vehiculo-by-id.main
#   events:
#     - httpApi: 'GET /veh/vehiculo/byId/{_id}'
#   package:
#     include:
#       - services/vehiculos/src/get-vehiculo-by-id.js
#       - lib/errors/database-error.js


