createRevision:
  name: ${self:custom.base}-create-revision
  handler: services/revisiones/src/create-revision.main
  events:
    - httpApi: 'POST /rev/revision'
  package:
    include:
      - services/revisiones/src/create-revision.js
      - lib/errors/database-error.js

getRevisiones:
  name: ${self:custom.base}-get-revisiones
  handler: services/revisiones/src/get-revisiones.main
  events:
    - httpApi: 'GET /rev/revision/{limit}/{start}/{busqueda}'
  package:
    include:
      - services/revisiones/src/get-revisiones.js
      - lib/errors/database-error.js

getRevisionByPunto:
  name: ${self:custom.base}-get-revision-by-punto
  handler: services/revisiones/src/get-revision-by-punto.main
  events:
    - httpApi: 'GET /rev/revision/byPunto/{_id}'
  package:
    include:
      - services/revisiones/src/get-revision-by-punto.js
      - lib/errors/database-error.js  

getRevisionById:
  name: ${self:custom.base}-get-revision-by-id
  handler: services/revisiones/src/get-revision-by-id.main
  events:
    - httpApi: 'GET /rev/revision/byId/{_id}'
  package:
    include:
      - services/revisiones/src/get-revision-by-id.js
      - lib/errors/database-error.js

addImages:
  name: ${self:custom.base}-add-images
  handler: services/revisiones/src/add-images.main
  timeout: 25
  events:
    - httpApi: 'PUT /rev/revision/add-images'
  environment:
    BUCKET: codegas
  package:
    include:
      - services/revisiones/src/add-images.js
      - lib/errors/database-error.js
      - lib/image.js
      - lib/responses.js

# removeImages:
#   name: ${self:custom.base}-remove-images
#   handler: services/revisiones/src/remove-images.main
#   timeout: 25
#   events:
#     - httpApi: 'PUT /tan/tanque/images/{idTanque}/{type}'
#   environment:
#     BUCKET: codegas
#   package:
#     include:
#       - services/revisiones/src/remove-images.js
#       - lib/errors/database-error.js
#       - lib/image.js
#       - lib/responses.js


revisionCoordenadas:
  name: ${self:custom.base}-revision-coordenadas
  handler: services/revisiones/src/revision-coordenadas.main
  events:
    - httpApi: 'PUT /rev/revision/coordenadas/{_id}'
  package:
    include:
      - services/revisiones/src/revision-coordenadas.js
      - lib/errors/database-error.js

