createTanque:
  name: ${self:custom.base}-create-tanque
  handler: services/tanques/src/create-tanque.main
  events:
    - httpApi: 'POST /tan/tanque'
  package:
    include:
      - services/tanques/src/create-tanque.js
      - lib/errors/database-error.js

getTanques:
  name: ${self:custom.base}-get-tanques
  handler: services/tanques/src/get-tanques.main
  events:
    - httpApi: 'GET /tan/tanque/{limit}/{start}/{busqueda}'
  package:
    include:
      - services/tanques/src/get-tanques.js
      - lib/errors/database-error.js

addImages:
  name: ${self:custom.base}-add-images
  handler: services/tanques/src/add-images.main
  events:
    - httpApi: 'PUT /tan/tanque/images/{idTanque}/{type}'
  environment:
    BUCKET: codegas
  package:
    include:
      - services/tanques/src/add-images.js
      - lib/errors/database-error.js
      - lib/image.js
      - lib/responses.js

addUser:
  name: ${self:custom.base}-add-user-tanque
  handler: services/tanques/src/add-user-tanque.main
  events:
    - httpApi: 'PUT /tan/tanque/add-user'
  package:
    include:
      - services/tanques/src/add-user-tanque.js
      - lib/errors/database-error.js

 