getUsers:
  name: ${self:custom.base}-get-users
  handler: services/informes/src/get-users.main
  events:
    - httpApi: 'GET /informe/users/{acceso}/{start}/{end}/{nombre}'
  package:
    include:
      - services/informes/src/get-users.js
      - lib/errors/database-error.js

getPedidos:
  name: ${self:custom.base}-get-pedidos
  handler: services/informes/src/get-pedidos.main
  events:
    - httpApi: 'GET /informe/pedidos/{type}/{start}/{end}/{nombre}'
  package:
    include:
      - services/informes/src/get-pedidos.js
      - lib/errors/database-error.js

getVehiculos:
  name: ${self:custom.base}-get-vehiculos
  handler: services/informes/src/get-vehiculos.main
  events:
    - httpApi: 'GET /informe/vehiculos/{start}/{end}/{nombre}'
  package:
    include:
      - services/informes/src/get-vehiculos.js
      - lib/errors/database-error.js

getTanques:
  name: ${self:custom.base}-get-tanques
  handler: services/informes/src/get-tanques.main
  events:
    - httpApi: 'GET /informe/tanques/{start}/{end}/{nombre}'
  package:
    include:
      - services/informes/src/get-tanques.js
      - lib/errors/database-error.js

getRevisiones:
  name: ${self:custom.base}-get-revisiones
  handler: services/informes/src/get-revisiones.main
  events:
    - httpApi: 'GET /informe/revisiones/{start}/{end}/{nombre}'
  package:
    include:
      - services/informes/src/get-revisiones.js
      - lib/errors/database-error.js
