createUser:
  name: ${self:custom.base}-save-user
  handler: services/users/src/save-user.main
  events:
    - httpApi: 'POST /users'
  package:
    include:
      - services/users/src/save-user.js
      - lib/errors/database-error.js

getUsers:
  name: ${self:custom.base}-get-users
  handler: services/users/src/get-users.main
  events:
    - httpApi: 'GET /users'
  package:
    include:
      - services/users/src/get-users.js
      - lib/errors/database-error.js

getUserByUid:
  name: ${self:custom.base}-get-user-by-uid
  handler: services/users/src/get-user-by-uid.main
  events:
    - httpApi: 'GET /users/perfil/{uid}'
  package:
    include:
      - services/users/src/get-user-by-uid.js
      - lib/errors/database-error.js